spring:
   datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: Database!
    url: jdbc:mysql://transaction-trigger-tracker.mariadb.database.azure.com:3306/banking_database
    username: tttracker@transaction-trigger-tracker
    
